### ISSUE TITLE
After upgrading to 1.0.0. The dmg output is incorrect.

### ISSUE THREAD

**Issue by Prince2k3** [advoryanskiy/fastlane-plugin-dmg#6]
I updated to version 1.0.0 just recently and noticed that when loading the dmg image the `.app` file is no longer present  but the `Content` folder is. I didn't make any changes to my fastlane file either.

**Fastfile**
```
dmg(
      path: "#{output_directory}/MyApp.app/",
      size: 10
 )
```

**Screenshot**
<img width="1032" alt="Screenshot 2023-02-05 at 9 12 02 PM" src="https://user-images.githubusercontent.com/2805285/216875944-12d8c068-79de-4e85-8de1-dee02ca47be7.png">

**Comment by anfalas** [comment]
same problem here.

**Comment by Prince2k3** [comment]
@advoryanskiy Could you give us an update? Is there a way we are supposed to configure our FastFile to get this to work?

**Comment by advoryanskiy** [comment]
@Prince2k3 @anfalas as a workaround you can configure `path` to parent folder for `.app`, like this:

```
dmg(
      path: "#{output_directory}/",
      size: 10
 )
```

**Comment by advoryanskiy** [comment]
`v1.0.1` released with a fix for this issue
